apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-deployment
spec:
  replicas: 20
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: test-app
        image: my-test-app:latest
        envFrom:
          - secretRef:
              name: test-app-secrets
        ports:
        - containerPort: 4000